// Builds the customer website for static hosting (e.g. Netlify): copies only the public website files
// into website-dist/ and writes config.js from environment variables, so live URLs are never committed.
//
//   CHINU_API_URL           backend URL, e.g. https://chinu-dhaba-api.onrender.com
//   CHINU_AI_URL            AI assistant URL, e.g. https://chinu-dhaba-ai.onrender.com
//   CHINU_ONLINE_PAYMENTS   "true" to offer "Pay online" (needs Razorpay keys on the backend)
//   CHINU_ADMIN_URL         admin dashboard URL: adds a "Restaurant staff" link to the footer
//
//   npm run build:website
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'website-dist');
const FILES = ['index.html', 'app.js', 'styles.css', 'effects.css', 'effects.js'];
const FOLDERS = ['assets/menu', 'assets/site'];

const url = (name) => {
  const value = String(process.env[name] || '').trim().replace(/\/+$/, '');
  if (value && !/^https?:\/\/[^\s]+$/.test(value)) {
    throw new Error(`${name} must be a full http(s) URL, got "${value}"`);
  }
  return value;
};

const config = {
  apiBaseUrl: url('CHINU_API_URL'),
  onlinePayments: String(process.env.CHINU_ONLINE_PAYMENTS || '').toLowerCase() === 'true',
  aiAssistantUrl: url('CHINU_AI_URL'),
  adminUrl: url('CHINU_ADMIN_URL'),
};

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
for (const file of FILES) fs.copyFileSync(path.join(ROOT, file), path.join(OUT, file));
for (const folder of FOLDERS) fs.cpSync(path.join(ROOT, folder), path.join(OUT, folder), { recursive: true });
fs.writeFileSync(
  path.join(OUT, 'config.js'),
  `// Generated by scripts/build-website.js from environment variables. Do not edit by hand.\nwindow.CHINU_CONFIG = ${JSON.stringify(config, null, 2)};\n`
);

console.log(`Website built in ${path.relative(ROOT, OUT)}/`);
console.log(`  backend: ${config.apiBaseUrl || '(none: demo mode, browser-only orders)'}`);
console.log(`  AI chat: ${config.aiAssistantUrl || '(off)'}`);
console.log(`  online payment: ${config.onlinePayments ? 'on' : 'off'}`);
console.log(`  staff link: ${config.adminUrl || '(off)'}`);
